import type { Database } from "./types";

// Deterministic seed data so a fresh install has a populated, believable
// marketplace to explore. Loaded once into the JSON store on first run.
export function seedData(): Database {
  const now = "2026-07-01T09:00:00.000Z";

  const users = [
    { id: "u_admin", name: "RentGear Ops", email: "ops@rentgear.co", role: "admin" as const, createdAt: now },
    { id: "u_dana", name: "Dana Whitfield", email: "dana@example.com", role: "lender" as const, createdAt: now },
    { id: "u_marco", name: "Marco Reyes", email: "marco@example.com", role: "lender" as const, createdAt: now },
    { id: "u_leah", name: "Leah Nguyen", email: "leah@example.com", role: "lender" as const, createdAt: now },
    { id: "u_sam", name: "Sam Carter", email: "sam@example.com", role: "renter" as const, createdAt: now },
    { id: "u_priya", name: "Priya Anand", email: "priya@example.com", role: "renter" as const, createdAt: now },
  ];

  const hubs = [
    {
      id: "h_riverside",
      name: "Riverside Hub",
      address: "128 Water St",
      city: "Boulder",
      region: "CO",
      lat: 40.0176,
      lng: -105.2797,
      hours: "Mon–Sat 8am–7pm, Sun 9am–5pm",
      phone: "(303) 555-0142",
    },
    {
      id: "h_summit",
      name: "Summit Gateway Hub",
      address: "4402 Alpine Ave",
      city: "Denver",
      region: "CO",
      lat: 39.7392,
      lng: -104.9903,
      hours: "Daily 7am–8pm",
      phone: "(303) 555-0188",
    },
    {
      id: "h_lakeside",
      name: "Lakeside Depot",
      address: "9 Marina Loop",
      city: "Fort Collins",
      region: "CO",
      lat: 40.5853,
      lng: -105.0844,
      hours: "Wed–Sun 8am–6pm",
      phone: "(970) 555-0121",
    },
  ];

  const categories = [
    { id: "c_camp", name: "Camping", slug: "camping", emoji: "⛺", blurb: "Tents, sleeping systems, and cook kits." },
    { id: "c_climb", name: "Climbing", slug: "climbing", emoji: "🧗", blurb: "Ropes, harnesses, and protection." },
    { id: "c_water", name: "Water Sports", slug: "water-sports", emoji: "🛶", blurb: "Kayaks, paddleboards, and dry gear." },
    { id: "c_snow", name: "Snow", slug: "snow", emoji: "🎿", blurb: "Skis, snowboards, and avalanche safety." },
    { id: "c_bike", name: "Cycling", slug: "cycling", emoji: "🚵", blurb: "Mountain and gravel bikes." },
    { id: "c_hike", name: "Hiking & Packs", slug: "hiking", emoji: "🥾", blurb: "Backpacks, poles, and navigation." },
  ];

  const gear = [
    {
      id: "g_tent4",
      name: "4-Season Basecamp Tent",
      description:
        "Roomy 4-person mountaineering tent that shrugs off wind and snow. Sleeps four comfortably with a large vestibule for packs.",
      categoryId: "c_camp",
      ownerId: "u_dana",
      hubId: "h_riverside",
      dailyPrice: 32,
      depositAmount: 120,
      replacementValue: 620,
      condition: "excellent" as const,
      brand: "Ridgeline",
      emoji: "⛺",
      status: "available" as const,
      createdAt: now,
    },
    {
      id: "g_bag0",
      name: "0°F Down Sleeping Bag",
      description: "Ultralight 800-fill down bag rated to 0°F. Packs down small; stays warm on alpine nights.",
      categoryId: "c_camp",
      ownerId: "u_dana",
      hubId: "h_summit",
      dailyPrice: 14,
      depositAmount: 60,
      replacementValue: 340,
      condition: "good" as const,
      brand: "Nimbus",
      emoji: "🛌",
      status: "available" as const,
      createdAt: now,
    },
    {
      id: "g_stove",
      name: "Backpacking Stove Kit",
      description: "Compact canister stove with pot set and windscreen. Boils a liter in under four minutes.",
      categoryId: "c_camp",
      ownerId: "u_marco",
      hubId: "h_riverside",
      dailyPrice: 8,
      depositAmount: 25,
      replacementValue: 95,
      condition: "good" as const,
      brand: "EmberPro",
      emoji: "🔥",
      status: "available" as const,
      createdAt: now,
    },
    {
      id: "g_rope",
      name: "60m Dynamic Climbing Rope",
      description: "Single dynamic rope, 9.8mm x 60m. Low use, dry-treated, retired-log kept up to date.",
      categoryId: "c_climb",
      ownerId: "u_marco",
      hubId: "h_summit",
      dailyPrice: 18,
      depositAmount: 80,
      replacementValue: 220,
      condition: "good" as const,
      brand: "Belay",
      emoji: "🪢",
      status: "available" as const,
      createdAt: now,
    },
    {
      id: "g_harness",
      name: "Sport Climbing Harness",
      description: "Adjustable all-around harness with four gear loops. Sizes M–L.",
      categoryId: "c_climb",
      ownerId: "u_leah",
      hubId: "h_summit",
      dailyPrice: 7,
      depositAmount: 30,
      replacementValue: 85,
      condition: "excellent" as const,
      brand: "Crag",
      emoji: "🧗",
      status: "rented" as const,
      createdAt: now,
    },
    {
      id: "g_kayak",
      name: "Touring Sea Kayak",
      description: "Stable 14ft touring kayak with rudder and dry storage. Paddle and spray skirt included.",
      categoryId: "c_water",
      ownerId: "u_leah",
      hubId: "h_lakeside",
      dailyPrice: 45,
      depositAmount: 200,
      replacementValue: 1400,
      condition: "excellent" as const,
      brand: "TideRunner",
      emoji: "🛶",
      status: "available" as const,
      createdAt: now,
    },
    {
      id: "g_sup",
      name: "Inflatable Paddleboard",
      description: "All-around inflatable SUP with pump, paddle, and leash. Great for flatwater and gentle rivers.",
      categoryId: "c_water",
      ownerId: "u_dana",
      hubId: "h_lakeside",
      dailyPrice: 28,
      depositAmount: 100,
      replacementValue: 560,
      condition: "good" as const,
      brand: "GlideCo",
      emoji: "🏄",
      status: "available" as const,
      createdAt: now,
    },
    {
      id: "g_skis",
      name: "All-Mountain Ski Package",
      description: "Skis, bindings, and poles tuned for all-mountain days. Sizes 170cm. Boots not included.",
      categoryId: "c_snow",
      ownerId: "u_marco",
      hubId: "h_summit",
      dailyPrice: 38,
      depositAmount: 150,
      replacementValue: 780,
      condition: "good" as const,
      brand: "PeakLine",
      emoji: "🎿",
      status: "available" as const,
      createdAt: now,
    },
    {
      id: "g_beacon",
      name: "Avalanche Safety Kit",
      description: "Beacon, probe, and shovel bundle. Beacon batteries fresh; quick pre-trip check at pickup.",
      categoryId: "c_snow",
      ownerId: "u_leah",
      hubId: "h_summit",
      dailyPrice: 16,
      depositAmount: 90,
      replacementValue: 430,
      condition: "excellent" as const,
      brand: "SafePass",
      emoji: "🚨",
      status: "maintenance" as const,
      createdAt: now,
    },
    {
      id: "g_mtb",
      name: "Full-Suspension Mountain Bike",
      description: "120mm trail bike, size L, dropper post and tubeless tires. Helmet available on request.",
      categoryId: "c_bike",
      ownerId: "u_dana",
      hubId: "h_riverside",
      dailyPrice: 55,
      depositAmount: 250,
      replacementValue: 2600,
      condition: "excellent" as const,
      brand: "TrailForge",
      emoji: "🚵",
      status: "available" as const,
      createdAt: now,
    },
    {
      id: "g_pack",
      name: "65L Expedition Backpack",
      description: "Adjustable-torso 65L pack with rain cover. Carries a multi-day load comfortably.",
      categoryId: "c_hike",
      ownerId: "u_marco",
      hubId: "h_riverside",
      dailyPrice: 11,
      depositAmount: 40,
      replacementValue: 260,
      condition: "good" as const,
      brand: "Cairn",
      emoji: "🎒",
      status: "available" as const,
      createdAt: now,
    },
    {
      id: "g_poles",
      name: "Carbon Trekking Poles",
      description: "Lightweight carbon poles with cork grips and quick-lock adjustment. Pair.",
      categoryId: "c_hike",
      ownerId: "u_leah",
      hubId: "h_lakeside",
      dailyPrice: 5,
      depositAmount: 20,
      replacementValue: 130,
      condition: "excellent" as const,
      brand: "Summit",
      emoji: "🥾",
      status: "available" as const,
      createdAt: now,
    },
    {
      id: "g_canoe",
      name: "Tandem Canoe",
      description: "16ft tandem canoe with two paddles and life vests. Stable for lakes and mellow rivers.",
      categoryId: "c_water",
      ownerId: "u_marco",
      hubId: "h_lakeside",
      dailyPrice: 40,
      depositAmount: 180,
      replacementValue: 1100,
      condition: "good" as const,
      brand: "TideRunner",
      emoji: "🛶",
      status: "pending" as const,
      createdAt: now,
    },
  ];

  const rentals = [
    {
      id: "r_0001",
      gearId: "g_harness",
      renterId: "u_sam",
      startDate: "2026-07-25",
      endDate: "2026-07-30",
      pickupHubId: "h_summit",
      dropoffHubId: "h_summit",
      days: 5,
      dailyPrice: 7,
      subtotal: 35,
      serviceFee: 8.75,
      ownerPayout: 26.25,
      deposit: 30,
      total: 73.75,
      status: "active" as const,
      createdAt: "2026-07-20T14:00:00.000Z",
    },
    {
      id: "r_0002",
      gearId: "g_mtb",
      renterId: "u_priya",
      startDate: "2026-07-10",
      endDate: "2026-07-12",
      pickupHubId: "h_riverside",
      dropoffHubId: "h_riverside",
      days: 2,
      dailyPrice: 55,
      subtotal: 110,
      serviceFee: 27.5,
      ownerPayout: 82.5,
      deposit: 250,
      total: 387.5,
      status: "completed" as const,
      createdAt: "2026-07-05T10:00:00.000Z",
    },
  ];

  return { users, hubs, categories, gear, rentals };
}
